services:
  web:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - mynetwork
    restart: always
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ujian
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

  queue:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - "15672:15672" 
      - "5672:5672"
    networks:
      - mynetwork
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
